# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoliageSsq',
            fields=[
                ('num', models.FloatField(primary_key=True, serialize=False)),
                ('r1', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('r3', models.FloatField(blank=True, null=True)),
                ('r4', models.FloatField(blank=True, null=True)),
                ('r5', models.FloatField(blank=True, null=True)),
                ('r6', models.FloatField(blank=True, null=True)),
                ('b1', models.FloatField(blank=True, null=True)),
                ('sum1', models.FloatField(blank=True, null=True)),
                ('sum2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foliage_ssq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSsqShishibiao',
            fields=[
                ('num', models.FloatField(primary_key=True, serialize=False)),
                ('waijian', models.FloatField(blank=True, null=True)),
                ('taoshu', models.FloatField(blank=True, null=True)),
                ('r1', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('r3', models.FloatField(blank=True, null=True)),
                ('r4', models.FloatField(blank=True, null=True)),
                ('r5', models.FloatField(blank=True, null=True)),
                ('r6', models.FloatField(blank=True, null=True)),
                ('b1', models.FloatField(blank=True, null=True)),
                ('sum1', models.FloatField(blank=True, null=True)),
                ('sum2', models.FloatField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_ssq_shishibiao',
                'managed': False,
            },
        ),
    ]
