# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foliagessq',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tssqshishibiao',
            options={'managed': False},
        ),
    ]
