# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuang', '0002_auto_20160331_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoliageSsq_ext',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('horizontal_span1', models.IntegerField(blank=True, null=True)),
                ('horizontal_span2', models.IntegerField(blank=True, null=True)),
                ('horizontal_span3', models.IntegerField(blank=True, null=True)),
                ('horizontal_span4', models.IntegerField(blank=True, null=True)),
                ('horizontal_span5', models.IntegerField(blank=True, null=True)),
                ('red_sum', models.IntegerField(blank=True, null=True)),
                ('prime_reds', models.IntegerField(blank=True, null=True)),
                ('odd_reds', models.IntegerField(blank=True, null=True)),
                ('red_weihe', models.IntegerField(blank=True, null=True)),
                ('red_lianhaoshu', models.IntegerField(blank=True, null=True)),
                ('red_shouweikuadu', models.IntegerField(blank=True, null=True)),
                ('attribute1', models.IntegerField(blank=True, null=True)),
                ('attribute2', models.IntegerField(blank=True, null=True)),
                ('attribute3', models.IntegerField(blank=True, null=True)),
                ('attribute4', models.IntegerField(blank=True, null=True)),
                ('attribute5', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foliagessq_ext',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='formula_fact_per',
            fields=[
                ('per_id', models.IntegerField(primary_key=True, serialize=False)),
                ('periods', models.IntegerField()),
                ('fact_id', models.IntegerField()),
                ('result', models.BooleanField()),
                ('formula_id', models.IntegerField()),
                ('formula_in5', models.FloatField()),
                ('formula_in10', models.FloatField()),
                ('formula_in30', models.FloatField()),
                ('formula_in50', models.FloatField()),
                ('formula_in100', models.FloatField()),
                ('formula_total', models.FloatField()),
            ],
            options={
                'db_table': 'formula_fact_per',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ssq_formula',
            fields=[
                ('formula_id', models.IntegerField(primary_key=True, serialize=False)),
                ('formula_name', models.CharField(max_length=100)),
                ('formula_express', models.CharField(max_length=100)),
                ('formula_note', models.CharField(max_length=200)),
                ('attribute1', models.CharField(max_length=100, null=True)),
                ('attribute2', models.CharField(max_length=100, null=True)),
                ('attribute3', models.CharField(max_length=100, null=True)),
                ('attribute4', models.CharField(max_length=100, null=True)),
                ('attribute5', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'ssq_formula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ssq_formula_fact',
            fields=[
                ('fact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('periods', models.IntegerField()),
                ('result', models.BooleanField()),
                ('formula_value', models.CharField(max_length=100)),
                ('attribute1', models.CharField(max_length=100, null=True)),
                ('attribute2', models.CharField(max_length=100, null=True)),
                ('attribute3', models.CharField(max_length=100, null=True)),
                ('attribute4', models.CharField(max_length=100, null=True)),
                ('attribute5', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'ssq_formula_fact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TSsqShishibiao_ext',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('horizontal_span1', models.IntegerField(blank=True, null=True)),
                ('horizontal_span2', models.IntegerField(blank=True, null=True)),
                ('horizontal_span3', models.IntegerField(blank=True, null=True)),
                ('horizontal_span4', models.IntegerField(blank=True, null=True)),
                ('horizontal_span5', models.IntegerField(blank=True, null=True)),
                ('vertical_blue', models.IntegerField(blank=True, null=True)),
                ('vertical_red1', models.IntegerField(blank=True, null=True)),
                ('vertical_red2', models.IntegerField(blank=True, null=True)),
                ('vertical_red3', models.IntegerField(blank=True, null=True)),
                ('vertical_red4', models.IntegerField(blank=True, null=True)),
                ('vertical_red5', models.IntegerField(blank=True, null=True)),
                ('vertical_red6', models.IntegerField(blank=True, null=True)),
                ('red_sum', models.IntegerField(blank=True, null=True)),
                ('prime_reds', models.IntegerField(blank=True, null=True)),
                ('odd_reds', models.IntegerField(blank=True, null=True)),
                ('red_weihe', models.IntegerField(blank=True, null=True)),
                ('red_lianhaoshu', models.IntegerField(blank=True, null=True)),
                ('red_shouweikuadu', models.IntegerField(blank=True, null=True)),
                ('attribute1', models.IntegerField(blank=True, null=True)),
                ('attribute2', models.IntegerField(blank=True, null=True)),
                ('attribute3', models.IntegerField(blank=True, null=True)),
                ('attribute4', models.IntegerField(blank=True, null=True)),
                ('attribute5', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tssqshishibiao_ext',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='tssqshishibiao',
            options={'managed': True},
        ),
    ]
