# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuang', '0003_auto_20160415_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foliagessq_ext',
            name='id',
            field=models.IntegerField(db_tablespace='USERS', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formula_fact_per',
            name='per_id',
            field=models.IntegerField(db_tablespace='USERS', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ssq_formula',
            name='formula_id',
            field=models.IntegerField(db_tablespace='USERS', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ssq_formula_fact',
            name='fact_id',
            field=models.IntegerField(db_tablespace='USERS', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='b1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='num',
            field=models.IntegerField(db_tablespace='USERS', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='r1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='r2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='r3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='r4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='r5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='r6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='sum1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='sum2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='taoshu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao',
            name='waijian',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao_ext',
            name='id',
            field=models.IntegerField(db_tablespace='USERS', primary_key=True, serialize=False),
        ),
    ]
