# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuang', '0004_auto_20160415_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foliagessq_ext',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tssqshishibiao_ext',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
