# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuang', '0005_auto_20160415_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula_fact_per',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ssq_formula',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ssq_formula',
            name='formula_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ssq_formula',
            name='update_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ssq_formula_fact',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ssq_formula_fact',
            name='formula_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
